CREATE TABLE public.music_genre (
	id_genre int8 NOT NULL GENERATED ALWAYS AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE),
	name_genre varchar NOT NULL,
	CONSTRAINT music_genre_pk PRIMARY KEY (id_genre)
);

CREATE TABLE public.musician_performer (
	id_musician int8 NOT NULL GENERATED ALWAYS AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE),
	musician_name varchar NOT NULL,
	CONSTRAINT musician_performer_pk PRIMARY KEY (id_musician)
);

CREATE TABLE public.genre_performer (
	id_genre int8 NOT NULL,
	id_musician int8 NOT NULL,
	CONSTRAINT genre_performer_pk PRIMARY KEY (id_genre, id_musician),
	CONSTRAINT genre_performer_fk FOREIGN KEY (id_genre) REFERENCES public.music_genre(id_genre),
	CONSTRAINT genre_performer_fk_1 FOREIGN KEY (id_musician) REFERENCES public.musician_performer(id_musician)
);

CREATE TABLE public.album (
	id_album int8 NOT NULL GENERATED ALWAYS AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE),
	album_name varchar NOT NULL,
	"year" int8 NULL,
	CONSTRAINT album_pk PRIMARY KEY (id_album)
);

CREATE TABLE public.musician_album (
	id_musician int8 NOT NULL,
	id_album int8 NOT NULL,
	CONSTRAINT musician_album_pk PRIMARY KEY (id_musician, id_album),
	CONSTRAINT musician_album_fk FOREIGN KEY (id_musician) REFERENCES public.musician_performer(id_musician),
	CONSTRAINT musician_album_fk_1 FOREIGN KEY (id_album) REFERENCES public.album(id_album)
);

CREATE TABLE public.track (
	id_track int8 NOT NULL GENERATED ALWAYS AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE),
	"name" varchar NOT NULL,
	id_album int8 NOT NULL,
	duration time NULL,
	CONSTRAINT track_pk PRIMARY KEY (id_track),
	CONSTRAINT track_fk FOREIGN KEY (id_album) REFERENCES public.album(id_album)
);

CREATE TABLE public.music_collection (
	id_collection int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE),
	collection_name varchar NOT NULL,
	"year" int8 NULL,
	CONSTRAINT music_collection_pk PRIMARY KEY (id_collection)
);

CREATE TABLE public.track_collection (
	id_track int8 NOT NULL,
	id_collection int8 NOT NULL,
	CONSTRAINT track_collection_pk PRIMARY KEY (id_track, id_collection),
	CONSTRAINT track_collection_fk FOREIGN KEY (id_collection) REFERENCES public.music_collection(id_collection),
	CONSTRAINT track_collection_fk_2 FOREIGN KEY (id_track) REFERENCES public.track(id_track)
);
